### ISSUE TITLE
Speed space chart is blinking

### ISSUE THREAD

**Issue by flomonster** [osrd-project/osrd-ui#427] opened 2024-09-04 08:43 UTC
### What happened?

Open all context information.
When we are moving the mouse over the speed space chart, it blinks. Same when we zoom in and out.

`Speed Limit Tag` is the most visible blinking component. 

### What did you expect to happen?

We should not see the chart blinking.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go [here](https://openrailassociation.github.io/osrd-ui/?path=/story/speedspacechart-rendering--speed-space-chart-default)
2. Open all context information.
3. Play around

**Comment by Castavo** [comment] 2024-10-24 13:18
@Synar The GEV is now WAY less blinky (thanks a lot) but still a little bit (see video below) (especially dezooming at max dezoom works fine to make it blink)

Would you mind if I reopened this issue ? Otherwise, I'll open another bug but it still fills like the same bug


https://github.com/user-attachments/assets/22d147ec-e464-4fb3-b050-5549bc88afc4

**Comment by Synar** [comment] 2024-10-24 16:49
As you wish for the issue

As for the blinking I'll look into it ^^

**Comment by Castavo** [comment] 2024-10-25 12:31
Thanks, I'll just reopen it then
And move it back into your board also (sorry if it's too much)

Thanks again for the huge improvements already made

**Comment by Tguisnet** [comment] 2024-11-28 14:45
There is a big improvement on this problem, this is pretty cool, thanks !
However, during the testing, there is still a little blinking on speed limit tag when we zoom

**Comment by Synar** [comment] 2024-11-28 15:02
https://github.com/user-attachments/assets/47dde9c5-3eba-4b8b-aab2-1c6292b7c157

I can't reproduce

**Comment by flomonster** [comment] 2024-11-29 10:51
> I can't reproduce

Can you try to reproduce the bug with the component integrated to OSRD (and with real data)

**Comment by Synar** [comment] 2024-11-29 11:07
> > I can't reproduce
> 
> Can you try to reproduce the bug with the component integrated to OSRD (and with real data)

Has the osrd-ui version been bumped on osrd? If not, the fix should not be live, and the bug should still be present there. But Tguisnet was saying he could reproduce the bug on the ui storybook, where it should be fixed.

**Comment by Castavo** [comment] 2024-11-29 11:44
The bug can indeed be reproduced on story-book, however, the story book is aligned with releases so the fix hasn't been deployed there either

**Comment by Tguisnet** [comment] 2024-11-29 11:49
As @Castavo said, it was tested on the deployed storybook, this version of storybook is based on the latest release of osrd-ui;
Checking the dates, the release was made one day before the last PR, so it’s probably not on the version we tested !
So It seems to be fix thanks :) !
(I close this issue)

**Closed as completed by Tguisnet** 2024-11-29 11:49 UTC
Labels: kind:bug, module:ui-speed-space-chart, severity:major, area:front

**Comment by Synar** [comment] 2024-11-29 11:51
Nice thanks!
